//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcunMedyaAkademiPortfolyo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblEducation
    {
        public int EducationId { get; set; }
        public string School { get; set; }
        public string Area { get; set; }
        public string ShortDescription { get; set; }
        public string Description { get; set; }
        public string Date { get; set; }
    }
}
